### ISSUE TITLE
Doesn’t work anymore.

### ISSUE THREAD

**Issue by s1nnohlakes** [deton24/MVSEP-MDX23-Colab_v2.1#2]
Not sure if this is still supported but as of a few days ago, it stopped working. Additionally, larger memory usage can be seen when using `onnxruntime-gpu` version 1.16.0 and above. I did workaround through this temporarily by creating my own fork and changing the version of it to 1.15.1, but ultimately this stopped working and it returns this error; `Failed to created CUDAExecutionProvider`. The newest version (2.3) did had a fix for this but this doesn’t work with `onnxruntime-gpu` 1.15.1.

Any way you could update this to fix it?

**Comment by deton24** [comment]
Maybe using Tools>Command pallette> Use fallback runtime will fix the issue?
At least it fixes the problem with onnxruntime warnings and slow MDX models
processing in other notebooks.

wt., 26 gru 2023, 10:24 użytkownik MGIsHere ***@***.***>
napisał:

**Comment by s1nnohlakes** [comment]
Tried this, and it worked! Though I’m not sure if this workaround will last long as Colab’s fallback runtime version is only available for a few months usually. Still, thank you for the tip!

**Comment by deton24** [comment]
Then adding line:
console('apt-get install cuda-11-8')
should do the trick (at least that's how it is for MDX-Net Colab). But it
takes 8m 30s to execute.
Meanwhile, Microsoft works on onnxruntime fix, and possibly it will fix
itself when the fix will be out.

śr., 27 gru 2023 o 01:59 MGIsHere ***@***.***> napisał(a):

**Comment by deton24** [comment]
Added permanent fix. Luckily it's fast. Thanks to jarredou.

console('pip3 -q install ort-nightly-gpu --index-url=
https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
')

Unified installation lines.
Decreased default chunks to 100000 as none other value worked for at least 3:00 track.

czw., 28 gru 2023 o 03:05 deton24 ***@***.***> napisał(a):

**Comment by s1nnohlakes** [comment]
Thank you so much! One last question before closing this issue, with chunk size now set to a lower value, does it affect quality by a lot or is it negligible?

**Comment by deton24** [comment]
A bit. Not that much, but still.
Anyway, I haven't seen any other option than decrease without turning off
denoiser in Demucs like jarredou did in hot fix for 2.0 version.
You can test SDR on MVSEP.
I was also curious about the best settings for SDR with this bag of models
in 2.1.
E.g. comparison with shifts set to 0 in inference, but with higher overlaps
instead, as it should be a little bit faster, but probably it will only
affect instrum2 result as it's probably only Demucs setting. Still, it can
sound a little bit muddier/a bit denoised than instrum. Depends on a song
what is the best. Most people don't notice any difference.

Looks like Google messed up sth few months ago, because people reported me
that memory issue before, but I didn't have it when I tested while doing
that fork. Now I reopened the Colab and tried to use it, and almost nothing
worked. I think only this one particular chunk setting or lower, so I lower
minimum value. It never happened before.



pt., 29 gru 2023, 02:32 użytkownik MGIsHere ***@***.***>
napisał:

**Comment by s1nnohlakes** [comment]
Got it. Thanks. Closing this issue now.
